# Generated by Django 5.0.3 on 2024-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=50)),
                ('Descrption', models.CharField(max_length=50)),
                ('image', models.ImageField(default='a', upload_to='statics/images')),
                ('ar', models.CharField(choices=[('a', 'a'), ('b', 'b')], default='a', max_length=50)),
                ('text', models.TextField(default='a')),
                ('boole', models.BooleanField(default=False)),
                ('url1', models.URLField(default='https://www.google.com')),
            ],
        ),
    ]
