# Generated by Django 5.0.3 on 2024-04-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abc',
            old_name='Descrption',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='abc',
            old_name='Heading',
            new_name='receipe_name',
        ),
        migrations.RemoveField(
            model_name='abc',
            name='image',
        ),
        migrations.AlterField(
            model_name='abc',
            name='ar',
            field=models.CharField(choices=[('Burger', 'Burger'), ('Snacks', 'Snacks'), ('Bevearages', 'Bevearages')], default='a', max_length=50),
        ),
    ]
