# Generated by Django 5.0.3 on 2024-04-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_rename_descrption_abc_receipe_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abc',
            new_name='Receipe',
        ),
    ]
