# Generated by Django 5.0.3 on 2024-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_rename_abc_receipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='image',
            field=models.ImageField(default='a', upload_to='static/images'),
        ),
    ]
