# Generated by Django 5.0.3 on 2024-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_receipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='text',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='url1',
        ),
        migrations.AddField(
            model_name='receipe',
            name='price',
            field=models.CharField(default='10', max_length=50),
        ),
    ]
