# Generated by Django 5.0.3 on 2024-04-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_remove_receipe_text_remove_receipe_url1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='image',
            new_name='receipe_image',
        ),
    ]
