# Generated by Django 5.0.3 on 2024-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_rename_ar_receipe_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_image', models.ImageField(default='a', upload_to='images')),
                ('category', models.CharField(default='a', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='category',
        ),
    ]
