# Generated by Django 5.0.3 on 2024-04-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_category_remove_receipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='boole',
        ),
        migrations.AddField(
            model_name='category',
            name='receipe_description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.category'),
        ),
    ]
