# Generated by Django 5.0.3 on 2024-05-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='frame',
            new_name='fname',
        ),
    ]
